# Generated by Django 5.2.11 on 2026-03-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='from_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='to_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='type',
            field=models.IntegerField(choices=[(1, 'One Time Event'), (2, 'Daily Event'), (3, 'Weekly Event'), (4, 'Monthly Event'), (5, 'Semiannual Event'), (6, 'Per Use Event')]),
        ),
    ]
