# Generated by Django 5.2.11 on 2026-03-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_eventschedule_from_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('lab', 'Lab'), ('clinical', 'Clinical'), ('environment', 'Environment')], default='lab', max_length=50),
            preserve_default=False,
        ),
    ]
