# Generated by Django 5.2.11 on 2026-03-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_department_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdetails',
            name='parameter_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
