name: Quality-control-Backend Push Trigger

on:
  push:
    branches:
      - main
      - devops-build

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      #  Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      #  Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #  Build Backend Docker image
      - name: Build Docker image
        run: |
          docker build \
            -f devops/Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/vidai-backend:latest \
            .

      #  Push Backend Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/vidai-backend:latest

      #  Deploy Backend to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/vidai-backend:latest

            docker stop vidai-backend || true
            docker rm vidai-backend || true

            docker run -d \
              --restart always \
              --name vidai-backend \
              -p 9000:8000 \
              ${{ secrets.DOCKER_USERNAME }}/vidai-backend:latest

